# Generated by Django 5.0.3 on 2025-04-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petadd',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
