# Generated by Django 5.0.3 on 2025-04-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_petadd_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='petadd',
            name='is_for_adoption',
            field=models.BooleanField(default=False),
        ),
    ]
