# Generated by Django 5.0.3 on 2025-04-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_daycarerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='daycarerequest',
            name='pet_photo',
            field=models.ImageField(blank=True, null=True, upload_to='daycare_pets/'),
        ),
    ]
